### ISSUE TITLE
Caches broken tiles even if tile server returns 500 Internal Server Error

### ISSUE THREAD

**Issue by hugovk** [cbick/osmviz#4]
When using osm.createOSMImage with an OSM server with broken tiles (such as Stamen tiles at the moment), it cannot create the image (as expected?) and saves an HTML error text file as the cached .png file.

For example with London:

```
bbox = (51.505272562570596, 51.50927923742941, -0.13315286427556772, -0.12216653572443227)
zoom = 17

osm = OSMManager(image_manager=PILImageManager('RGB'),
                 server='http://d.tile.stamen.com/watercolor')
img, bnds = osm.createOSMImage(bbox, zoom)
```

Output:

```
  File "C:\Python27\lib\osmviz\manager.py", line 333, in createOSMImage
    self.manager.paste_image_file( fname, (x_off,y_off) )
  File "C:\Python27\lib\osmviz\manager.py", line 108, in paste_image_file
    raise Exception, "Could not load image "+str(imagef)+"\n"+str(e)
Exception: Could not load image C:\DOCUME~1\Hugo\LOCALS~1\Temp\osmviz-68701-17_65491_43585.png
```

And:

```
C:\Python27\Lib\osmviz>cat C:\DOCUME~1\Hugo\LOCALS~1\Temp\osmviz-68701-17_65491_43585.png

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>500 Internal Server Error</title>
  </head>
  <body>
    <h1>Error 500 Internal Server Error</h1>
    <p>Internal Server Error</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 912655379</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

Expected result:
Doesn't save the fake png, so I don't need to manually inspect and delete them afterwards, as the cached file would prevent later, re-generated tiles be saved.
Exception should be raised earlier in retrieveTileImage() rather than later in paste_image_file().

(Possibly osm.createOSMImage() could still return a generated image with some blank tile instead of the broken one, but still it shouldn't save broken tiles to disk.)

**Comment by davemenninger** [comment]
FWIW, Stamen tiles work with the .jpg extension, but OSMManager is hard-coded to expect png.

http://d.tile.stamen.com/watercolor/0/0/0.jpg  <-- works

Don't know it it's worth adding a type option in OSMManager or just wait for Stamen tiles to start supplying png files again.
